### ISSUE TITLE
News sources: Belgium

### ISSUE THREAD

**Issue by thibaultmol** [kagisearch/kite-public#1]
For Belgium these are the 'main' news sources that I know that have rss feeds:
(all of them are dutch unless it says it's french. if it's not an xml file then it's a page full of different categories of rss feeds)

# Public broadcasters
https://www.vrt.be/vrtnieuws/nl.rss.articles.xml
https://www.rtbf.be/article/le-flux-rss-mode-d-emploi-3266 # french
https://sporza.be/nl.rss.xml # sports

# Commercial news sites national
https://www.hln.be/home/rss.xml
https://www.demorgen.be/in-het-nieuws/rss.xml
https://www.lesoir.be/services/rss # french
https://www.standaard.be/rssfeeds
https://www.nieuwsblad.be/rss
https://www.lalibre.be/rss/about/ # french
https://www.tijd.be/rss/nieuws.xml
https://www.knack.be/feed/
https://www.metrotime.be/fr/rss & www.metrotime.be/nl/rss # these are currently broken it seems. have contacted them
http://www.sudinfo.be/feed/10127

# Commercial news sites local
https://www.gva.be/rss
https://www.hbvl.be/rss
https://www.bruzz.be/rss.xml
https://focus-wtv.be/feed/home.xml

# Smaller indie news sites
https://www.apache.be/feed/artikels # their articles are all paid BUT the first 24 hours they're all free (which obv means that the internet archive makes the whole website accessible xd .but for the purposes of Kite it's kinda prefect xd

**Comment by vprelovac** [comment]
ok once you have 20 feel free to submit an edit

**Comment by vprelovac** [comment]
want to submit a PR?

**Comment by thibaultmol** [comment]
see PR https://github.com/kagisearch/kite-public/pull/50
