### ISSUE TITLE
Brazilian feed add

### ISSUE THREAD

**Issue by TheLastEnvoy** [kagisearch/kite-public#2]
**Notes about each RSS provided (except the ones from Google News:**

- g1.globo.com
    - Category: general
    - Description: the biggest/most used source of news in Brazil
        - RSS: [https://g1.globo.com/dynamo/brasil/rss2.xml](https://g1.globo.com/dynamo/brasil/rss2.xml)

- ge.globo.com
    - Category: sports
    - Description: belongs to Globo, it's the biggest/most used source of sport news in Brazil
        - RSS: [https://ge.globo.com/Esportes/Rss/0](https://ge.globo.com/Esportes/Rss/0),,AS0-9645,00.xml

- canaltech.com.br
    - Category: technology
    - Description: one of the main source of news about technology, have some ADs though. Belong to Magazine Luiza (retail market)
        - RSS: [https://feeds2.feedburner.com/canaltechbr](https://feeds2.feedburner.com/canaltechbr)

- cinema.uol.com.br
    - Category: cinema
    - Description: big source of news about cinema in Brazil
        - RSS: [http://cinema.uol.com.br/ultnot/index.xml](http://cinema.uol.com.br/ultnot/index.xml)

- nexojornal.com.br
    - Category: politics
    - Description: one of the main "alternative" source of news about politics in Brazil
        - RSS: [https://www.nexojornal.com.br/rss.xml](https://www.nexojornal.com.br/rss.xml)

- agenciadenoticias.ibge.gov.br
    - Category: science
    - Description: the main brazilian agency of geography and statistics studies (state-owned institute)
        - [https://agenciadenoticias.ibge.gov.br/agencia-rss](https://agenciadenoticias.ibge.gov.br/agencia-rss)

- cartacapital.com.br
    - Category: politics
    - Description: source of news with a critical perspective
        - RSS: [https://www.cartacapital.com.br/feed](https://www.cartacapital.com.br/feed)

- bbc.com/portuguese/topicos/brasil
    - Category: general
    - Description: one of the main sources of news in Brazil
        - RSS: [http://www.bbc.co.uk/portuguese/topicos/brasil/index.xml](http://www.bbc.co.uk/portuguese/topicos/brasil/index.xml)

- folha.uol.com.br/ciencia
    - Category: science
    - Description: one of the main sources of news about science in Brazil
        - RSS: [https://feeds.folha.uol.com.br/ciencia/rss091.xml](https://feeds.folha.uol.com.br/ciencia/rss091.xml)

- noticias.uol.com.br
    - Category: general
    - Description: one of the main competitors of g1
        - RSS: [http://rss.uol.com.br/feed/noticias.xml](http://rss.uol.com.br/feed/noticias.xml)

- news.un.org/pt
    - Category: politics
    - Description: UN RSS Feed for South America (content in portuguese)
        - RSS: [https://news.un.org/feed/subscribe/pt/news/region/americas/feed/rss.xml](https://news.un.org/feed/subscribe/pt/news/region/americas/feed/rss.xml)

- agenciabrasil.ebc.com.br/internacional
    - Category: international
    - Description: source of news about international matters (state-owned agency)
        - RSS: [http://agenciabrasil.ebc.com.br/rss/internacional/feed.xml](http://agenciabrasil.ebc.com.br/rss/internacional/feed.xml)

- reporterbrasil.org.br
    - Category: politics
    - Description: alternative source of news about politics in Brazil
        - RSS: [https://reporterbrasil.org.br/categorias/noticias/feed/](https://reporterbrasil.org.br/categorias/noticias/feed/)

- portal.inmet.gov.br/noticias
    - Category: climate
    - Description: source of news about climate (state-owned institute)
        - RSS: [https://apiprevmet3.inmet.gov.br/avisos/rss](https://apiprevmet3.inmet.gov.br/avisos/rss)

- valor.globo.com
    - Category: economy
    - Description: one of the main sources of news about economy in Brazil
        - RSS: [http://pox.globo.com/rss/valor](http://pox.globo.com/rss/valor)

- uol.com.br/esporte
    - Category: sports
    - Description: one of the main competitors of ge.globo
        - RSS: [http://rss.esporte.uol.com.br/ultimas/index.xml](http://rss.esporte.uol.com.br/ultimas/index.xml)

- omelete.com.br
    - Category: cultural
    - Description: famous source of news about cultural content
        - RSS: [http://www.omelete.com.br/rss/rss.aspx](https://www.theenemy.com.br/rss/rss.aspx)

- revistaforum.com.br/ciencia-e-tecnologia
    - Category: technology, science
    - Description: alternative source of news about technology and science
        - RSS: [https://revistaforum.com.br/rss/feed.html?r=735](https://revistaforum.com.br/rss/feed.html?r=735)

- revistaforum.com.br/saude
    - Category: health
    - Description: alternative source of news about health
        - RSS: [https://revistaforum.com.br/rss/feed.html?r=727](https://revistaforum.com.br/rss/feed.html?r=727)

- revistaforum.com.br/brasil
    - Category: general
    - Description: alternative source of news in Brazil
        - RSS: [https://revistaforum.com.br/rss/feed.html?r=96](https://revistaforum.com.br/rss/feed.html?r=96)

**RSS for .json file:**

```
  "Brazil": {
    "feeds": [
      "https://g1.globo.com/dynamo/brasil/rss2.xml",
      "https://ge.globo.com/Esportes/Rss/0,,AS0-9645,00.xml",
      "https://feeds2.feedburner.com/canaltechbr",
      "http://cinema.uol.com.br/ultnot/index.xml",
      "https://www.nexojornal.com.br/rss.xml",
      "https://agenciadenoticias.ibge.gov.br/agencia-rss",
      "https://www.cartacapital.com.br/feed",
      "http://www.bbc.co.uk/portuguese/topicos/brasil/index.xml",
      "https://feeds.folha.uol.com.br/ciencia/rss091.xml",
      "http://rss.uol.com.br/feed/noticias.xml",
      "https://news.un.org/feed/subscribe/pt/news/region/americas/feed/rss.xml",
      "http://agenciabrasil.ebc.com.br/rss/internacional/feed.xml",
      "https://reporterbrasil.org.br/categorias/noticias/feed/",
      "https://apiprevmet3.inmet.gov.br/avisos/rss",
      "http://pox.globo.com/rss/valor",
      "http://rss.esporte.uol.com.br/ultimas/index.xml",
      "http://www.omelete.com.br/rss/rss.aspx",
      "https://revistaforum.com.br/rss/feed.html?r=735",
      "https://revistaforum.com.br/rss/feed.html?r=727",
      "https://revistaforum.com.br/rss/feed.html?r=96",
      "https://news.google.com/rss/topics/CAAqJQgKIh9DQkFTRVFvSUwyMHZNREUxWm5JU0JYQjBMVUpTS0FBUAE?hl=pt-BR&gl=BR&ceid=BR%3Apt-419",
      "https://news.google.com/rss/topics/CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx1YlY4U0JYQjBMVUpTR2dKQ1VpZ0FQAQ?hl=pt-BR&gl=BR&ceid=BR%3Apt-419",
      "https://news.google.com/rss/topics/CAAqLAgKIiZDQkFTRmdvSkwyMHZNR1ptZHpWbUVnVndkQzFDVWhvQ1FsSW9BQVAB?hl=pt-BR&gl=BR&ceid=BR%3Apt-419"
    ]
  }
}
```

**Comment by vprelovac** [comment]
Added! Thanks!
