### ISSUE TITLE
News sources: Estonia

### ISSUE THREAD

**Issue by azdanov** [kagisearch/kite-public#3]
I'd like to start gathering news sources for [Estonia](https://en.wikipedia.org/wiki/Estonia).

But it's a bit difficult since 20 is quite a high number for a smaller country. Will see how many sources I can find that are in English.

- https://news.err.ee/rss
- https://news.postimees.ee/rss
- https://estonianworld.com/feed/
- https://news.google.com/topics/CAAqIQgKIhtDQkFTRGdvSUwyMHZNREpyYlcwU0FtVnVLQUFQAQ?hl=en-US&gl=US&ceid=US%3Aen

**Comment by azdanov** [comment]
Here's what I found with mixed languages (Estonian, English, Russian, Ukrainian):

- https://www.err.ee/rss
- https://www.postimees.ee/rss
- https://online.le.ee/feed/
- https://gazeta.ee/feed/
- https://narvaleht.ee/feed/
- https://sonumitooja.ee/feed/
- https://kesknadal.ee/feed/
- https://koiduaeg.ee/feed/
- https://estonianworld.com/feed/
- https://digi.geenius.ee/feed/
- https://uueduudised.ee/feed/
- https://eestiuudised.ee/feed/
- https://www.ohtuleht.ee/rss
- https://www.ituudised.ee/rss
- https://www.aripaev.ee/rss
- https://www.ehitusuudised.ee/rss
- https://www.laanevirumaauudised.ee/rss
- https://eestikirik.ee/feed
- https://www.telegram.ee/feed
- https://kesknadal.ee/feed/
- https://www.tartu.ee/et/rss
- https://feeds.feedburner.com/aripaev-rss
- http://feeds2.feedburner.com/delfiuudised
- http://feeds2.feedburner.com/delfimaailm
- http://feeds2.feedburner.com/forteuudised
- https://www.reddit.com/r/Eesti.rss
- https://www.reddit.com/r/BalticStates.rss
- https://news.google.com/rss/topics/CAAqIQgKIhtDQkFTRGdvSUwyMHZNREpyYlcwU0FtVnVLQUFQAQ?hl=en-US&gl=US&ceid=US%3Aen&oc=11
- https://news.google.com/rss/topics/CAAqIQgKIhtDQkFTRGdvSUwyMHZNREpyYlcwU0FtVjBLQUFQAQ?hl=et-EE&gl=EE&ceid=EE%3Aet&oc=11
- https://news.google.com/rss/topics/CAAqJggKIiBDQkFTRWdvSUwyMHZNRGx1YlY4U0FtVjBHZ0pGUlNnQVAB?hl=et-EE&gl=EE&ceid=EE%3Aet&oc=11
- https://news.google.com/rss/topics/CAAqIQgKIhtDQkFTRGdvSUwyMHZNREpyYlcwU0FuSjFLQUFQAQ?hl=ru&gl=RU&ceid=RU%3Aru&oc=11
- https://news.google.com/rss/topics/CAAqIQgKIhtDQkFTRGdvSUwyMHZNREpyYlcwU0FuVnJLQUFQAQ?hl=uk&gl=UA&ceid=UA%3Auk&oc=11

**Comment by vprelovac** [comment]
I should have said we need 20 sources in the same language. Mixing languages makes grouping articles harder and the result will be subpar. I have merged it in but it will not be as good as other categories.

**Comment by azdanov** [comment]
I thought that LLMs could work with mixed content. I can remove all other languages apart from Estonian to increase the quality, would that be better?

**Comment by vprelovac** [comment]
We are not running everything through an LLM, that would not work at the scale of articles we need to process.

**Comment by tenseoverflow** [comment]
Some of these feeds are political party sponsored news feeds, like Kesknädal and Uued Uudised. There was also Objektiiv added in later commits. Should these be included?
