### ISSUE TITLE
News sources: European Union

### ISSUE THREAD

**Issue by azdanov** [kagisearch/kite-public#8]
I'd like to compile a feed for all the [EU countries](https://en.wikipedia.org/wiki/Member_state_of_the_European_Union#List). I'm choosing EU, since there is an official boundary of which countries are considered in EU, opposed to Europe, where one can argue that a country is in Europe or outside of it.

**Comment by vprelovac** [comment]
most big outlets have 'europe' section that we can leverage...

        "https://www.lemonde.fr/europe/rss_full.xml",
        "https://www.spiegel.de/international/europe/index.rss",
        "https://www.politico.eu/feed/",
        "https://rss.nytimes.com/services/xml/rss/nyt/Europe.xml",
        "http://feeds.bbci.co.uk/news/world/europe/rss.xml",
        "https://www.euronews.com/rss?level=program&name=europe-news",
        "https://www.ft.com/world/europe?format=rss",
        "https://www.economist.com/europe/rss.xml",
        "https://feeds.npr.org/1124/rss.xml",
        "https://www.euronews.com/rss?level=vertical&name=my-europe",
        "https://www.scmp.com/rss/322263/feed",

**Comment by azdanov** [comment]
```json
[
  "https://officialblogofunio.com/feed/",
  "https://ecipe.org/blog/feed/",
  "https://www.express.co.uk/latest/european-union/rss",
  "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/topic/organization/european-union/rss.xml",
  "http://eulawanalysis.blogspot.com/feeds/posts/default",
  "https://ecfr.eu/feed/",
  "https://www.euractiv.com/feed/"
]
```

**Comment by azdanov** [comment]
```
[
  "https://www.reddit.com/r/europe/.rss",
  "https://www.reddit.com/r/europes/.rss",
  "https://www.reddit.com/r/esa/.rss",
  "https://www.reddit.com/r/europeanparliament/.rss",
  "https://www.reddit.com/r/europeanunion/.rss",
  "https://www.reddit.com/r/EuropeanFederalists/.rss",
  "https://news.google.com/rss/topics/CAAqIQgKIhtDQkFTRGdvSUwyMHZNREpxT1hvU0FtVnVLQUFQAQ?hl=en-US&gl=US&ceid=US%3Aen&oc=11",
  "https://news.google.com/rss/topics/CAAqJAgKIh5DQkFTRUFvS0wyMHZNRjgyZEY5Nk9CSUNaVzRvQUFQAQ?hl=en-US&gl=US&ceid=US%3Aen&oc=11"
]
```
